# Generated by Django 5.2.10 on 2026-01-15 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("CONSULTATION", "Consultation"),
                            ("CANCELLATION_FEE", "Cancellation fee"),
                            ("NO_SHOW_FEE", "No-show fee"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "session_url",
                    models.URLField(blank=True, max_length=2048, null=True),
                ),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("money_to_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="appointment.appointment",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
