# Generated by Django 5.2.10 on 2026-01-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("CONSULTATION", "Consultation"),
                    ("CANCELLATION_FEE", "Cancellation fee"),
                    ("NO_SHOW_FEE", "No-show fee"),
                ],
                default="CONSULTATION",
                max_length=20,
            ),
        ),
    ]
