# Generated by Django 5.2.10 on 2026-01-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0003_alter_appointment_booked_at_and_more"),
        ("payment", "0004_payment_stripe_payment_intent_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("appointment", "payment_type"), name="unique_appointment"
            ),
        ),
    ]
