# Generated by Django 5.2.10 on 2026-01-15 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctor", "0002_doctorslot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Booked"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                        ],
                        default="BOOKED",
                        max_length=15,
                    ),
                ),
                ("booked_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=8),
                ),
                (
                    "doctor_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment",
                        to="doctor.doctorslot",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "appointment",
                "verbose_name_plural": "appointments",
                "ordering": ["-booked_at"],
            },
        ),
    ]
