# Generated by Django 5.2.10 on 2026-01-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="booked_at",
            field=models.DateTimeField(null=True),
        ),
    ]
