# Generated by Django 5.2.10 on 2026-01-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0002_alter_appointment_booked_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="booked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, editable=False, max_digits=8, null=True
            ),
        ),
    ]
