# Generated by Django 5.2.10 on 2026-01-22 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0003_alter_appointment_booked_at_and_more"),
        ("doctor", "0003_remove_doctor_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CANCELLED"), _negated=True),
                fields=("doctor_slot",),
                name="unique_active_slot_booking",
            ),
        ),
    ]
