# Generated by Django 5.2.10 on 2026-01-15 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_doctorslot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="user",
        ),
    ]
