# Generated by Django 5.2.10 on 2026-01-27 15:06

import django.contrib.postgres.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_remove_doctor_user"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="doctorslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("start__lt", models.F("end"))),
                name="start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="doctorslot",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    (
                        models.Func(
                            models.F("start"), models.F("end"), function="tstzrange"
                        ),
                        "&&",
                    )
                ],
                name="no_overlapping_slots",
            ),
        ),
    ]
